#include <iostream>
#include <string>

using namespace std;

int main()
{
   string raptor_prompt_variable_zzyz;
   int spades,
	   heartsTotal,
	   diamonds,
	   spadesTotal,
	   runTimes,
	   diamondsTotal,
	   deals,
	   clubsTotal,
	   runCount,
	   cardNumber,
	   clubs,
	   hearts;

   cardNumber =0;
   deals =0;
   clubs =0;
   clubsTotal =0;
   diamonds =0;
   diamondsTotal =0;
   hearts =0;
   heartsTotal =0;
   spades =0;
   spadesTotal =0;
   runTimes =0;
   runCount =1;
   cout << "Welcome to the Card Dealing Simulator" << endl;
   cout << "This program will simulate dealing a single card from a deck 1000 times and then display how many times each suit gets dealt.  You will be able to specify how many runs (of 1000 deals) to perform." << endl;
   raptor_prompt_variable_zzyz ="How many runs would you like to perform? ";
   cout << raptor_prompt_variable_zzyz;
   cin >> runTimes;
   while (1)
   {
      while (1)
      {
		  // generated by Raptor
//		  cardNumber = floor((random_generator.NextDouble() * 52) + 1);
		  cardNumber = rand() % 52 + 1;
		  if (cardNumber<=13)
         {
            clubs =clubs+1;
         }
         else
         {
            if (cardNumber<=26)
            {
               diamonds =diamonds+1;
            }
            else
            {
               if (cardNumber<=39)
               {
                  hearts =hearts+1;
               }
               else
               {
                  spades =spades+1;
               }
            }
         }
         deals =deals+1;
         if (deals==1000) break;
      }
      heartsTotal =heartsTotal+hearts;
      clubsTotal =clubsTotal+clubs;
      diamondsTotal =diamondsTotal+diamonds;
      spadesTotal =spadesTotal+spades;
      cout << "Run #" << runCount << ":  Hearts = " << hearts << ", Spades = " << spades << ", Clubs = " << clubs << ", Diamonds = " << diamonds << endl;
	  if (runTimes==runCount) break;
      runCount =runCount+1;
      clubs =0;
      diamonds =0;
      hearts =0;
      spades =0;
      deals =0;
   }
   if (runTimes > 1) {
	   cout << "Totals after " << runTimes << " runs:" << endl;
	   cout << "Hearts = " << heartsTotal << ", Spades = " << spadesTotal << ", Clubs = " << clubsTotal << ", Diamonds = " << diamondsTotal << endl;
   }

   return 0;
}